language: c
sudo: true

jobs:
  include:
  - os: linux
    dist: focal

before_install:
  - mkdir -p ./fpc-3.3.1.x86_64-linux
  - tar -xvzf ./fpascal/fpc-3.3.1.x86_64-linux.tar.gz -C ./fpc-3.3.1.x86_64-linux
  - export PATH="./fpc-3.3.1.x86_64-linux/bin:$PATH"
  - ./fpc-3.3.1.x86_64-linux/bin/fpc -iW

install:
  - cat kjvbible.txt kjvbible.txt kjvbible.txt kjvbible.txt kjvbible.txt kjvbible.txt kjvbible.txt kjvbible.txt kjvbible.txt kjvbible.txt >kjvbible_x10.txt
  - ./fpc-3.3.1.x86_64-linux/bin/fpc -B -Ci- -Cr- -Fi./fpascal/lgenerics/lgenerics -Fu./fpascal -FU./fpascal/lib -Fu./fpascal/lgenerics/lgenerics -g- -O4 -o./fpascal/optimized-pascal -XXs ./fpascal/optimized.pas
  - go build -o optimized-go optimized.go

script:
  - set -e
  - echo Free Pascal optimized
  - time ./fpascal/optimized-pascal <kjvbible_x10.txt | python3 normalize.py >output.txt
  - time ./fpascal/optimized-pascal <kjvbible_x10.txt | python3 normalize.py >output.txt
  - time ./fpascal/optimized-pascal <kjvbible_x10.txt | python3 normalize.py >output.txt
  - time ./fpascal/optimized-pascal <kjvbible_x10.txt | python3 normalize.py >output.txt
  - time ./fpascal/optimized-pascal <kjvbible_x10.txt | python3 normalize.py >output.txt  
  - git diff --exit-code output.txt
  - echo Go optimized
  - time ./optimized-go <kjvbible_x10.txt | python3 normalize.py >output.txt
  - time ./optimized-go <kjvbible_x10.txt | python3 normalize.py >output.txt
  - time ./optimized-go <kjvbible_x10.txt | python3 normalize.py >output.txt
  - time ./optimized-go <kjvbible_x10.txt | python3 normalize.py >output.txt
  - time ./optimized-go <kjvbible_x10.txt | python3 normalize.py >output.txt
  - git diff --exit-code output.txt

